version: '3'
services:
  master:
    build:
      args:
        base: redis:6.2.7
      context: .
    command:
    - redis-server
    - /usr/local/etc/redis_master.conf
    container_name: master
    healthcheck:
      interval: 2s
      retries: 10
      test:
      - CMD
      - redis-cli
      - ping
      timeout: 2s
  slave1:
    build:
      args:
        base: redis:6.2.7
      context: .
    command:
    - redis-server
    - /usr/local/etc/redis_slave.conf
    container_name: slave1
    depends_on:
      master:
        condition: service_healthy
  slave2:
    build:
      args:
        base: redis:6.2.7
      context: .
    command:
    - redis-server
    - /usr/local/etc/redis_slave.conf
    container_name: slave2
    depends_on:
      master:
        condition: service_healthy
